### ISSUE TITLE
How to remove svg background image back_cube_dm.svg

### ISSUE THREAD

**Issue by DalekDave** [ipbc-dev/peertube-theme-bittube-dark-mode#2]
This is not a bug, it's more of a question:

I am using the theme on my instance, but I would live to remove the back_cube-dm.svg background image. I tried overwriting it in /var/www/peertube/storage/plugins/node_modules/peertube-theme-bittube-dark-mode/public/images/ with a blank svg image, but the original background pattern will not disappear!

Please could you explain if I have to recompile the theme or something?

Thank you in advance for any help.

**Comment by ipbc-dev** [comment]
To do so, you will need to manually reinstall your modified version of the plugin. I use this commands in my server:
node ./dist/server/tools/peertube.js auth add -u 'https://bittube.video' -U 'root' --password 'Zhnujm123!!!'

node ./dist/server/tools/peertube.js plugins install -u 'https://bittube.video' -U 'root' --password 'Zhnujm123!!!' --path /var/www/peertube/peertube-theme-bittube-dark-mode

**Comment by ipbc-dev** [comment]
To do so, you will need to manually reinstall your modified version of the plugin. I use this commands in my server:
node ./dist/server/tools/peertube.js auth add -u 'https://your.instance' -U 'root' --password 'YourPassword'

node ./dist/server/tools/peertube.js plugins install -u 'https://your.instance' -U 'root' --password 'YourPassword' --path /path/to/modified/plugin/peertube-theme-bittube-dark-mode

**Comment by ipbc-dev** [comment]
I have created two new versions without background: 
- https://github.com/ipbc-dev/peertube-theme-bittube-dark-mode-no-background
- https://github.com/ipbc-dev/peertube-theme-bittube-light-mode-no-background

They should be available in a pair of days

**Comment by DalekDave** [comment]
Sorry to respond so late. I just wanted to say thank you for creating the alternative no-background-svg theme. And thank you for the tips on how to recompile assets. :+1:
