### ISSUE TITLE
White navbars on some pages after updating to PeerTube version 3.2.1

### ISSUE THREAD

**Issue by TILvids** [ipbc-dev/peertube-theme-bittube-dark-mode#6]
Specifically the top of the "About" page, the top of the "Administration" page, etc. All of them are now solid white with very light gray text. Issue appeared after updating to PeerTube 3.2.1 and was not resolved with latest update to bittube-dark-mode 2.1.4.

**Comment by ipbc-dev** [comment]
-- Please reply above this line --


Hello!

We received your request and will get in touch with you as soon as
possible.

We usually reply WITHIN 24 HOURS BETWEEN MONDAY TO FRIDAY.

In the meantime, you can have a look at the BitTube Knowledge Base:
https://kb.bittube.app [1] and reply to this email with 'SOLVED', if
you found the answer to your question.

Thanks for your understanding.

Talk to you soon,

BitTube Team.


Links:
------
[1] https://kb.bittube.app

**Comment by TILvids** [comment]
This issue is still happening.

**Comment by ipbc-dev** [comment]
We had some issues with 3.2.0 release so we were not able to fix it. Peertube fixed their issues on this new 3.3.0 release so, we already fixed it on "bittube-dark-mode 3.0.0" and "bittube-dark-mode-no-background 3.0.1". Sorry for the inconvenience and thanks for reporting!!

**Comment by TILvids** [comment]
Excellent, and not a problem. Will look forward to the update. Thank you for your nice work!
